select * from Customers;
select * from Orders;
select * from OrderDetails;
select * from Products;
select * from Inventory;
-- Write an SQL query to find out which customers have not placed any orders.
select Firstname , CustomerID from Customers where CustomerID <> all(select CustomerID from Orders);
-- Write an SQL query to find the total number of products available for sale.
 select sum(QuantityinStock) Total from Inventory;
 -- Write an SQL query to calculate the total revenue generated by TechShop. 
 select sum(TotalAmount)from Orders;
 -- Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter.-- Write an SQL query to calculate the total revenue generated by a specific customer. Allow users to input the customer ID as a parameter
 select CustomerID , sum(TotalAmount) from Orders where CustomerID = any (select CustomerID from Customers )group by CustomerID;
 -- Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed.
 select CustomerID ,count(*) from Orders where CustomerID = any (select CustomerID from Customers)group by CustomerID;
 -- Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders.
 select Products.ProductName , OrderDetails.Quantity from Products inner join OrderDetails on Products.ProductID = OrderDetails.ProductID where OrderDetails.Quantity = (select max(OrderDetails.Quantity) from OrderDetails);
 -- Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending
 SELECT Customers.FirstName,Customers.LastName,Orders.TotalAmount AS TotalRevenue FROM Orders JOIN Customers ON orders.CustomerID = Customers.CustomerID WHERE Orders.TotalAmount = (SELECT MAX(TotalAmount) FROM Orders);
 -- Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers
 select Customers.FirstName,Customers.LastName,avg(TotalAmount)from Customers inner join Orders on Customers.CustomerID = Orders.CustomerID group by Customers.CustomerID;
 -- Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count